import Head from "next/head";
import Footer from "./Footer";
import Navbar from "./Navbar";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Ninja List | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="ninja" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="content">
        <Navbar />
        {children}
        <Footer />
      </div>
    </>
  );
}
